import "server-only";
import type { Lead } from "../crm/types";
import { LEAD_HEADERS } from "./mappers";

/**
 * Development fixture used ONLY while the Sheets service account is not
 * configured (never silently in production). It reproduces every §9 data
 * problem — six phone formats, leading-zero and malformed postcodes,
 * mixed stage-date formats, a speed-to-lead outlier with a thousands
 * comma, duplicates, unassigned leads and an append-blob Notes field —
 * so downstream phases are built against realistic dirt, not clean data.
 */

type MockLead = Partial<Record<keyof Lead, string>> & { uniqueId: string };

const LEAD_FIELDS = Object.keys(LEAD_HEADERS) as (keyof Lead)[];

function leadRow(l: MockLead): string[] {
  return LEAD_FIELDS.map((f) => l[f] ?? "");
}

const MOCK_LEADS: MockLead[] = [
  {
    uniqueId: "10101",
    dateAdded: "21/07/2026 09:12:44",
    firstName: "Judith",
    lastName: "Crawford",
    email: "judith.crawford@gmail.com",
    phone: "0274 471 988",
    postCode: "0110",
    stage: "Lead",
    agent: "Sarah Mitchell",
    agentEmail: "sarah@meloyelo.nz",
    city: "Whangārei",
    viewUpdateUrl: "https://docs.google.com/forms/d/e/mock/viewform?entry.1=10101",
    liveUpdateLink: "https://script.google.com/macros/s/mock/exec?id=10101",
    source: "Website Form",
  },
  {
    uniqueId: "10102",
    dateAdded: "15/07/2026 08:40:02",
    firstName: "Tom",
    lastName: "Baxter",
    email: "tom.baxter@gmail.com",
    phone: "21721560",
    postCode: "1010",
    stage: "Made contact",
    agent: "Dave Thompson",
    agentEmail: "dave@meloyelo.nz",
    city: "Auckland",
    notes:
      "10:05am 16/07/26 Dave Thompson: Called, interested in the commuter range. Sending brochure.",
    stageUpdatedAt: "16/07/2026 10:05:11",
    stageUpdateFrom: "Lead",
    stageUpdateTo: "Made contact",
    speedToLeadMinutes: "1493",
    source: "Website Form",
    viewUpdateUrl: "https://docs.google.com/forms/d/e/mock/viewform?entry.1=10102",
    liveUpdateLink: "https://script.google.com/macros/s/mock/exec?id=10102",
  },
  {
    uniqueId: "10103",
    dateAdded: "08/07/2026 08:13:27",
    firstName: "Aroha",
    lastName: "Ngata",
    email: "aroha.ngata@gmail.com",
    phone: "+64 272471230",
    postCode: "6011",
    stage: "Test Ride Booked",
    agent: "Priya Patel",
    agentEmail: "priya@meloyelo.nz",
    city: "Wellington",
    notes:
      "10:15am 08/07/26 Priya Patel: Called, keen on a test ride this weekend.\n2:47pm 10/07/26 Priya Patel: Booked test ride for Saturday at the Wellington hub. Wants the step-through model — mentioned her partner may come along too, which could mean a second sale if the ride goes well. Bring both frame sizes and the comfort saddle option, plus the finance one-pager since she asked about weekly payments twice. Parking is tight near her office so meet at the waterfront entrance. She is comparing us against a second-hand petrol scooter, so emphasise running costs and the servicing plan.",
    stageUpdatedAt: "2:47pm 10/07/26",
    stageUpdateFrom: "Made contact",
    stageUpdateTo: "Test Ride Booked",
    speedToLeadMinutes: "122",
    source: "Website Form",
    viewUpdateUrl: "https://docs.google.com/forms/d/e/mock/viewform?entry.1=10103",
    liveUpdateLink: "https://script.google.com/macros/s/mock/exec?id=10103",
  },
  {
    uniqueId: "10104",
    dateAdded: "12/05/2026 11:20:19",
    firstName: "Bill",
    lastName: "Sutton",
    email: "bill.sutton@xtra.co.nz",
    phone: "027-272-6680",
    postCode: "8011",
    stage: "MY Customer",
    agent: "Mike O'Brien",
    agentEmail: "mike@meloyelo.nz",
    city: "Christchurch",
    model: "Tasman GT",
    serial: "MY23-8842",
    regMatchKey: "bill.sutton@xtra.co.nz|MY23-8842",
    stageUpdatedAt: "20/05/2026 16:44:52",
    stageUpdateFrom: "Offer Accepted",
    stageUpdateTo: "MY Customer",
    speedToLeadMinutes: "45",
    source: "Warranty Registration",
    viewUpdateUrl: "https://docs.google.com/forms/d/e/mock/viewform?entry.1=10104",
    liveUpdateLink: "https://script.google.com/macros/s/mock/exec?id=10104",
  },
  {
    // Unassigned: malformed postcode broke routing (§9.2, §9.6)
    uniqueId: "10105",
    dateAdded: "17/07/2026 13:02:51",
    firstName: "Karen",
    lastName: "White",
    email: "karen.white@gmail.com",
    phone: "640274332406",
    postCode: "07020",
    stage: "Lead",
    city: "Auckland",
    alert48Sent: "TRUE",
    source: "Call Centre",
    viewUpdateUrl: "https://docs.google.com/forms/d/e/mock/viewform?entry.1=10105",
    liveUpdateLink: "https://script.google.com/macros/s/mock/exec?id=10105",
  },
  {
    // Duplicate person #1 (§9.5) + speed outlier with comma (§9.3)
    uniqueId: "10106",
    dateAdded: "02/06/2026 10:11:38",
    firstName: "Grace",
    lastName: "Lin",
    email: "grace.lin@gmail.com",
    phone: "0272 471 230",
    postCode: "1021",
    stage: "Contact Failed",
    agent: "Dave Thompson",
    agentEmail: "dave@meloyelo.nz",
    city: "Auckland",
    stageUpdatedAt: "05/06/2026 09:30:00",
    stageUpdateFrom: "Lead",
    stageUpdateTo: "Contact Failed",
    speedToLeadMinutes: "306,447",
    alert48Sent: "TRUE",
    alert5DaySent: "TRUE",
    source: "Website Form",
    viewUpdateUrl: "https://docs.google.com/forms/d/e/mock/viewform?entry.1=10106",
    liveUpdateLink: "https://script.google.com/macros/s/mock/exec?id=10106",
  },
  {
    // Duplicate person #2 — same human, different email
    uniqueId: "10107",
    dateAdded: "19/07/2026 15:47:20",
    firstName: "Grace",
    lastName: "Lin",
    email: "gracelin88@hotmail.com",
    phone: "0272471230",
    postCode: "1021",
    stage: "Lead",
    agent: "Dave Thompson",
    agentEmail: "dave@meloyelo.nz",
    city: "Auckland",
    source: "AgentForm",
    viewUpdateUrl: "https://docs.google.com/forms/d/e/mock/viewform?entry.1=10107",
    liveUpdateLink: "https://script.google.com/macros/s/mock/exec?id=10107",
  },
  {
    // Two people sharing one email (§9.5)
    uniqueId: "10108",
    dateAdded: "28/06/2026 09:55:07",
    firstName: "Ray & June",
    lastName: "Hodges",
    email: "hodges.family@xtra.co.nz",
    phone: "03 384 2210",
    postCode: "8014",
    stage: "Test Ride Completed",
    agent: "Mike O'Brien",
    agentEmail: "mike@meloyelo.nz",
    city: "Christchurch",
    notes:
      "9:20am 30/06/26 Mike O'Brien: Both came for the ride, June loved the Kea. Ray undecided.",
    stageUpdatedAt: "30/06/2026 09:20:44",
    stageUpdateFrom: "Test Ride Booked",
    stageUpdateTo: "Test Ride Completed",
    speedToLeadMinutes: "2210",
    source: "Website Form",
    viewUpdateUrl: "https://docs.google.com/forms/d/e/mock/viewform?entry.1=10108",
    liveUpdateLink: "https://script.google.com/macros/s/mock/exec?id=10108",
  },
  {
    // Unassigned: no postcode at all (§9.6)
    uniqueId: "10109",
    dateAdded: "20/07/2026 18:31:10",
    firstName: "Peter",
    lastName: "Kowalski",
    email: "p.kowalski@gmail.com",
    phone: "0210 224 7788",
    stage: "Lead",
    city: "Hamilton",
    source: "Website Form",
    viewUpdateUrl: "https://docs.google.com/forms/d/e/mock/viewform?entry.1=10109",
    liveUpdateLink: "https://script.google.com/macros/s/mock/exec?id=10109",
  },
  {
    uniqueId: "10110",
    dateAdded: "10/07/2026 12:09:33",
    firstName: "Nina",
    lastName: "Solomona",
    email: "nina.solomona@gmail.com",
    phone: "022 641 8853",
    postCode: "0110",
    stage: "Offer Accepted",
    agent: "Sarah Mitchell",
    agentEmail: "sarah@meloyelo.nz",
    city: "Whangārei",
    notes:
      "11:02am 12/07/26 Sarah Mitchell: Test ride done, loved it.\n2:15pm 18/07/26 Sarah Mitchell: Accepted the offer, arranging delivery.",
    stageUpdatedAt: "18/07/2026 14:22:03",
    stageUpdateFrom: "Test Ride Completed",
    stageUpdateTo: "Offer Accepted",
    speedToLeadMinutes: "88",
    source: "Website Form",
    viewUpdateUrl: "https://docs.google.com/forms/d/e/mock/viewform?entry.1=10110",
    liveUpdateLink: "https://script.google.com/macros/s/mock/exec?id=10110",
  },
  {
    uniqueId: "10111",
    dateAdded: "01/07/2026 14:00:58",
    firstName: "Alistair",
    lastName: "Finch",
    email: "a.finch@outlook.com",
    phone: "04 385 0921",
    postCode: "6011",
    stage: "Test Ride Declined",
    agent: "Priya Patel",
    agentEmail: "priya@meloyelo.nz",
    city: "Wellington",
    stageUpdatedAt: "06/07/2026 10:12:40",
    stageUpdateFrom: "Made contact",
    stageUpdateTo: "Test Ride Declined",
    speedToLeadMinutes: "310",
    source: "Call Centre",
    viewUpdateUrl: "https://docs.google.com/forms/d/e/mock/viewform?entry.1=10111",
    liveUpdateLink: "https://script.google.com/macros/s/mock/exec?id=10111",
  },
  {
    // Stale "Made contact" — needs action (§11 Today)
    uniqueId: "10112",
    dateAdded: "11/07/2026 07:26:14",
    firstName: "Moana",
    lastName: "Rewi",
    email: "moana.rewi@gmail.com",
    phone: "027 555 0173",
    postCode: "1010",
    stage: "Made contact",
    agent: "Dave Thompson",
    agentEmail: "dave@meloyelo.nz",
    city: "Auckland",
    stageUpdatedAt: "12/07/2026 09:18:26",
    stageUpdateFrom: "Lead",
    stageUpdateTo: "Made contact",
    speedToLeadMinutes: "1552",
    alert48Sent: "TRUE",
    source: "Website Form",
    viewUpdateUrl: "https://docs.google.com/forms/d/e/mock/viewform?entry.1=10112",
    liveUpdateLink: "https://script.google.com/macros/s/mock/exec?id=10112",
  },
  {
    uniqueId: "10113",
    dateAdded: "18/06/2026 16:42:05",
    firstName: "Sam",
    lastName: "Porter",
    email: "sam.porter@gmail.com",
    phone: "0273 998 412",
    postCode: "8011",
    stage: "Offer Declined",
    agent: "Mike O'Brien",
    agentEmail: "mike@meloyelo.nz",
    city: "Christchurch",
    stageUpdatedAt: "02/07/2026 11:05:17",
    stageUpdateFrom: "Test Ride Completed",
    stageUpdateTo: "Offer Declined",
    speedToLeadMinutes: "664",
    source: "Website Form",
    viewUpdateUrl: "https://docs.google.com/forms/d/e/mock/viewform?entry.1=10113",
    liveUpdateLink: "https://script.google.com/macros/s/mock/exec?id=10113",
  },
  {
    // Brand new today — needs action
    uniqueId: "10114",
    dateAdded: "22/07/2026 07:58:00",
    firstName: "Lucy",
    lastName: "Harker",
    email: "lucy.harker@gmail.com",
    phone: "021 044 7810",
    postCode: "1010",
    stage: "Lead",
    agent: "Dave Thompson",
    agentEmail: "dave@meloyelo.nz",
    city: "Auckland",
    source: "Website Form",
    viewUpdateUrl: "https://docs.google.com/forms/d/e/mock/viewform?entry.1=10114",
    liveUpdateLink: "https://script.google.com/macros/s/mock/exec?id=10114",
  },
];

export const MOCK_TABS: Record<string, string[][]> = {
  "All data": [
    Object.values(LEAD_HEADERS) as string[],
    ...MOCK_LEADS.map(leadRow),
  ],
  Agents: [
    ["Agent Name", "Notification Email", "CRM Email", "Region"],
    ["Sarah Mitchell", "sarah.notify@meloyelo.nz", "sarah@meloyelo.nz", "Northland"],
    ["Dave Thompson", "dave.notify@meloyelo.nz", "dave@meloyelo.nz", "Auckland Central"],
    ["Priya Patel", "priya.notify@meloyelo.nz", "priya@meloyelo.nz", "Wellington"],
    ["Mike O'Brien", "mike.notify@meloyelo.nz", "mike@meloyelo.nz", "Canterbury"],
  ],
  Postcodes: [
    ["Post Code", "Agent", "Agent Email"],
    ["0110", "Sarah Mitchell", "sarah@meloyelo.nz"],
    ["0112", "Sarah Mitchell", "sarah@meloyelo.nz"],
    ["1010", "Dave Thompson", "dave@meloyelo.nz"],
    ["1021", "Dave Thompson", "dave@meloyelo.nz"],
    ["6011", "Priya Patel", "priya@meloyelo.nz"],
    ["6012", "Priya Patel", "priya@meloyelo.nz"],
    ["8011", "Mike O'Brien", "mike@meloyelo.nz"],
    ["8014", "Mike O'Brien", "mike@meloyelo.nz"],
  ],
  "Stage history": [
    ["Unique ID", "From", "To", "Changed At", "Agent"],
    ["10102", "Lead", "Made contact", "16/07/2026 10:05:11", "Dave Thompson"],
    ["10103", "Lead", "Made contact", "08/07/2026 10:15:40", "Priya Patel"],
    ["10103", "Made contact", "Test Ride Booked", "2:47pm 10/07/26", "Priya Patel"],
    ["10104", "Offer Accepted", "MY Customer", "20/05/2026 16:44:52", "Mike O'Brien"],
    ["10106", "Lead", "Contact Failed", "05/06/2026 09:30:00", "Dave Thompson"],
    ["10108", "Test Ride Booked", "Test Ride Completed", "30/06/2026 09:20:44", "Mike O'Brien"],
    ["10110", "Test Ride Completed", "Offer Accepted", "18/07/2026 14:22:03", "Sarah Mitchell"],
    ["10111", "Made contact", "Test Ride Declined", "06/07/2026 10:12:40", "Priya Patel"],
    ["10112", "Lead", "Made contact", "12/07/2026 09:18:26", "Dave Thompson"],
    ["10113", "Test Ride Completed", "Offer Declined", "02/07/2026 11:05:17", "Mike O'Brien"],
  ],
  Config: [
    ["Key", "Value"],
    ["UPDATE_FORM_ID", "mock-update-form-id"],
    ["LIVE_UPDATE_WEB_APP_URL", "https://script.google.com/macros/s/mock/exec"],
    ["HUB_API_SECRET", "mock-hub-secret"],
  ],
  Logs: [
    ["Timestamp", "Type", "Message"],
    ["22/07/2026 07:00:12", "INFO", "processNewContactSubmissionsBatch: 1 processed"],
    [
      "19/07/2026 03:12:09",
      "ERROR",
      "assignAgentByPostcode: postcode '07020' not found for 10105",
    ],
    ["18/07/2026 06:00:03", "INFO", "Call centre import: 3 rows"],
  ],
};
